mysite/asset/Blog_Clone_Project/blog_project/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
]

mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # home page will be the list of the post
    path('', views.PostListView.as_view(), name="post_list"),
    path('about/', views.AboutView.as_view(), name='about'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name="post_new"),
    path('post/edit/<int:pk>/', views.PostUpdateView.as_view(), name='post_edit'),
    path('drafts', views.DraftListView.as_view(), name='post_drafts_list'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name="post_remove"),
    path('register', views.sign_up, name='sign_up'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout_user'),
    path('publish_post/<int:pk>', views.publish_post, name='publish_post'),
    path('comment_form/<int:pk>', views.add_comment, name='add_comment'),
    path('remove_comment/<int:pk>', views.remove_comment, name='remove_comment'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Blog Project</title>
    <!-- Latest compiled and minified CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />

    <!-- Optional theme -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    />

    {# MEDIUM STYLE EDITOR#}
    <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css"
      type="text/css"
      media="screen"
      charset="utf-8"
    />
    <script
      src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"
      referrerpolicy="origin"
    ></script>

    {# Custom CSS#}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" />

    {# Fonts#}
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One"
      rel="stylesheet"
    />
  </head>

  <body class="loader">
    <nav class="navbar navbar-default techfont custom-navbar">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand bigbrand" href="#">BD Tech blog</a></li>

          <li><a href="{% url 'blog:post_list' %}">Home</a></li>
          <li><a href="https://www.github.com/tanviredu">Github</a></li>
          <li>
            <a href="https://www.linkedin.com/in/ornobtanvir">LinkedIn</a>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'blog:post_new' %}">New Post</a>
          </li>

          <li>
            <a href="{% url 'blog:post_drafts_list' %}">Drafts</a>
          </li>
          <li>
            <a
              href="{% url 'blog:logout_user' %}"
              onclick="return confirm('Are you sure?')"
              >Log out</a
            >
          </li>

          <li>
            <a>Welcome: {{ user.username }}</a>
          </li>
          {% else %}
          <li>
            <a class="nav navbar-right" href="#"
              ><span class="glyphicon glyphicon-user"></span
            ></a>
          </li>
          <li><a href="{% url 'blog:login' %}">Login</a></li>
          <li><a href="{% url 'blog:sign_up' %}">Register</a></li>

          {% endif %}
        </ul>
      </div>
    </nav>

    {# The actual blog posts#}
    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_posts">
            {% block content %} {% endblock %}
          </div>
        </div>
      </div>
    </div>

    {# SCRIPTS#}

    <script type="text/javascript" src="{% static 'js/blog.js' %}"></script>
  </body>
</html>